### ISSUE TITLE
not python3 compatible print statements

### ISSUE THREAD

**Issue by jcpeterson** [revbucket/mister_ed#2]
I would import future print and change `print ""` --> `print("")` everywhere

**Comment by jcpeterson** [comment]
also the use of `basestring` instaed of `str` and `.itervalues()` instead of `.values()` for dicts

**Comment by jcpeterson** [comment]
and use of `xrange`

**Comment by revbucket** [comment]
Noted. 

It's somewhere on a TODO list to make this python3 compatible, but for now, let's assume we only support python2.

For more memory-efficient iteration: 
- `xrange` isn't python3 compatible, so if anything, I should change from `xrange` to either range or iterators. 
- similarly with `itervalues` vs `values`

As it stands right now, I don't think this is causing any performance issues (if it looks like it is, please tell me!), and I'm hopeful that any of the not-so-memory-efficient things above cause any problems because the iterables themselves are fairly small in length.

**Comment by jcpeterson** [comment]
In my copy, I've changed all of those things I listed, plus a few more and it works fine so far.

**Comment by jcpeterson** [comment]
It only took me about an hour to convert this to be python3-compatible (and still work with python2), so I think it's worth it.

**Comment by revbucket** [comment]
Great! If you don't mind, could create a pull request so I can save the hour of time and fold it into master? 

I'll try to use python3 compatible coding on future commits, too

**Comment by jcpeterson** [comment]
I can probably do that in a few days. This seems to be the only pytorch repo of it's kind. Is that right?

**Comment by revbucket** [comment]
Okay sure. I can also do it sometime soon too (just not this week)

As far as I know, this repo is the closest thing to `cleverhans` implemented in pytorch. Foolbox apparently has pytorch support, but I haven't looked into it too deeply. 

And since I haven't tried to publicize this repo yet, if you have any usability comments or suggestions, please let me know! (either here, in another issue, or through my personal email)

**Comment by jcpeterson** [comment]
Will do!

**Comment by revbucket** [comment]
Also everything is python3 now. There might be some leftover bugs, but these should be fairly easy to catch when they pop up.
