### ISSUE TITLE
Is the imagenet model adversarially pretrained?

### ISSUE THREAD

**Issue by ghost** [revbucket/mister_ed#22]

**Comment by tianweiy** [comment]
No, because adv train takes 6 months of GPU time. If you use TensorFlow, you can refer to [URL](https://github.com/facebookresearch/ImageNet-Adversarial-Training) for adversarially trained imagenet models. According to this  [issue](https://github.com/facebookresearch/ImageNet-Adversarial-Training/issues/7), someone converts the model to PyTorch, but I didn't try it out yet.

**Comment by ghost** [comment]
Thanks, closing the issue.

**Comment by revbucket** [comment]
Reopening this real quick: 

Pretrained ImageNet models are taken from this repo: https://github.com/Cadene/pretrained-models.pytorch 

As Tianwei mentioned, there's a FAIR repo (which strangely is based in tensorflow) and some code to convert their models. If you can get this conversion working, or can find a pytorch adversarially trained ImageNet classifier, or if you make one yourself, please update this and we'll incorporate it into the repo.

**Comment by vietvo89** [comment]
Hello guys

I came into the same problem as yours and found the link below from Madry lab. Please check it out. https://github.com/MadryLab/robustness. 

I have not tested it successfully yet. Once I have done it I can share with you guys or if you guys find it work, please also share with me.
